### ISSUE TITLE
Support for Rest API

### ISSUE THREAD

**Issue by binyoh** [tchlyah/couchmove#20]
Currently CouchBase doesn't support FTS index creation via N1QL and I have to relay on Rest API. Will you be able to include RestAPI support in couchmove?

**Comment by tchlyah** [comment]
Couchmove is compatible with FTS since version [2.0](https://github.com/tchlyah/couchmove/releases/tag/2.0), you just need to add a changeling file with `.fts` extension containing FTS index in `JSON` format
