### ISSUE TITLE
Allow custom variables in scripts

### ISSUE THREAD

**Issue by larochef** [tchlyah/couchmove#22]
In Flyway, you can pass custom values to your migration scripts, this is really useful, and would need it.
The need I have right now is that the replication factor when creating indexes will not be the same in dev or in prod, so I need a way to pass it correctly to have scripts that will stay the same in all the environments.

I will submit a MR for it shortly

**Comment by larochef** [comment]
@tchlyah do you think it could be included? Or is the project dead?

**Comment by tchlyah** [comment]
Sorry @larochef, I'm in the middle of a relocation, so it is tough to work on open source projects. But no, the project is not dead, I'm maintaining it as much as possible. Let me take a look.

**Comment by larochef** [comment]
Hi @tchlyah do you think you could release a version for it?

**Comment by tchlyah** [comment]
Hi @larochef, a new version has been released: [3.3.1](https://oss.sonatype.org/service/local/repositories/releases/content/com/github/differentway/couchmove/3.3.1/couchmove-3.3.1.pom)

**Comment by larochef** [comment]
Great, thx!
