### ISSUE TITLE
Build package of version 3.4 for maven repository

### ISSUE THREAD

**Issue by vhbmsp** [tchlyah/couchmove#49]
Hi there! Is it possible to build the package of version 3.4 for maven repository? Currently only V3.2.2 is available and that version uses guava-31.0 which has known vulnerabilities. V3.4 already fixes that with the use of guava-32 which is OK.

Thank you
Vasco Pinheiro

**Comment by tchlyah** [comment]
Hi! Sorry for the oversight, I have released version [3.4.1](https://repo1.maven.org/maven2/com/github/differentway/couchmove/3.4.1/)
