### ISSUE TITLE
Standalone executable

### ISSUE THREAD

**Issue by rukavina** [tchlyah/couchmove#6]
Hi,

This seems to be exactly like flyway replacement for couchbase. I'm not familiar with Java and its tooling. So I'm not sure if this is a lib or there is standalone executable with command line/config file options to run migrations? Or even better to be run as docker container?

**Comment by tchlyah** [comment]
Hello, this is a great idea, I'll try to implement this as soon as I have enough time. Contributions to help are welcome!

**Comment by technok** [comment]
Hi, Please can I know if this feature would be available soon ?

**Comment by tchlyah** [comment]
Sorry for taking so long, I finally find the opportunity and the time to work on this. It is part of [3.4](https://github.com/tchlyah/couchmove/releases/tag/v3.4) release.

You can download the binaries for each platform and java application, but you can also use it with docker: [ghcr.io/tchlyah/couchmove:v3.4](https://github.com/tchlyah/couchmove/pkgs/container/couchmove/119922165?tag=v3.4)

I'll document everything pretty soon.
